version: '2'
services:
  tracker:
    build: .
    ports:
        - 91:80
    volumes:
        - ./:/var/www
        - ./docker/logs/:/var/log
    env_file:
        - ./.env
    container_name: tracker
    depends_on:
        - mysql

  mysql:
      image: mysql:5.6
      container_name: mysql
      environment:
          # with mysql
          MYSQL_DATABASE: tracker
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
      volumes:
          - ./docker/data/mysql:/var/lib/mysql
      ports:
          - "3309:3306"